/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("me.apqx.kotlin-application-conventions")

}

group = "me.apqx"
version = "1.0.0"

dependencies {

}

application {
    // Define the main class for the application.
    mainClass.set("me.apqx.app.AppKt")
}
