/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id ("org.jetbrains.kotlin.jvm")
    application
}

group = "me.apqx"
version = "1.0.0"

dependencies {
    implementation(Dependencies.KOTLIN_COROUTINE)
    implementation(Dependencies.KTOR_CLIENT_OKHTTP)
    implementation(Dependencies.KTOR_CLIENT_CORE)
    implementation(Dependencies.KTOR_CLIENT_LOG)
    implementation(Dependencies.KTOR_CLIENT_CONTENT_NEGOTIATATION)
    implementation(Dependencies.KTOR_CLIENT_SERIALIZATION_GSON)

    testImplementation(Dependencies.JUNIT_JUPITER)
}

application {
    // Define the main class for the application.
    mainClass.set("me.apqx.app.AppKt")
}
